repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-toml # checks toml files for parseable syntax.
      - id: check-xml # checks xml files for parseable syntax.
      - id: check-yaml # checks yaml files for parseable syntax.
  # ðŸ§¹ Ruff for linting, import sorting, and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.5
    hooks:
      - id: clang-format
        files: ^spy/libspy
        types_or: [c, c++]
        exclude: ^spy/libspy/vendored/
